services:
  master:
    build: .
    image: elastic-torch-worker
    container_name: master_worker
    restart: always
    command: >
      torchrun
        --nproc_per_node=1
        --nnodes=1:4
        --rdzv_id=elastic_job_123
        --rdzv_backend=c10d
        --max-restarts=3
        --rdzv_endpoint=master_worker:29400
        worker.py
    volumes:
      - ./checkpoints:/app/checkpoints
    networks:
      - torch_net

  worker:
    build: .
    image: elastic-torch-worker
    restart: always
    command: >
      torchrun
        --nproc_per_node=1
        --nnodes=1:4
        --max-restarts=3
        --rdzv_id=elastic_job_123
        --rdzv_backend=c10d
        --rdzv_endpoint=master_worker:29400
        worker.py
    volumes:
      - ./checkpoints:/app/checkpoints
    networks:
      - torch_net
    depends_on:
      master:
        condition: service_started

networks:
  torch_net:
    driver: bridge