version: '3.8'

services:
  master:
    build: .
    image: pytorch-orchestrator:latest
    container_name: pytorch-master
    environment:
      - RANK=0
      - WORLD_SIZE=2
      - MASTER_ADDR=master
      - MASTER_PORT=29500
    command:
      - "--epochs=10"
      - "--steps=20"
      - "--checkpoint_interval=5"
      - "--checkpoint_dir=/app/checkpoints"
    volumes:
      - ./checkpoints:/app/checkpoints

  worker-1:
    build: .
    image: pytorch-orchestrator:latest
    container_name: pytorch-worker-1
    depends_on:
      - master
    environment:
      - RANK=1
      - WORLD_SIZE=2
      - MASTER_ADDR=master
      - MASTER_PORT=29500
    command:
      - "--epochs=10"
      - "--steps=20"
      - "--checkpoint_interval=5"
      - "--checkpoint_dir=/app/checkpoints"
    volumes:
      - ./checkpoints:/app/checkpoints
