services:
  master:
    build: .
    image: elastic-torch-worker
    container_name: master_worker
    command: >
      torchrun
        --nproc_per_node=1
        --nnodes=1:3
        --rdzv_id=elastic_job_123
        --rdzv_backend=c10d
        --rdzv_endpoint=master_worker:29400
        worker.py
    volumes:
      - ./checkpoints:/app/checkpoints
    networks:
      - torch_net

  worker:
    build: .
    image: elastic-torch-worker
    command: >
      torchrun
        --nproc_per_node=1
        --nnodes=1:3
        --rdzv_id=elastic_job_123
        --rdzv_backend=c10d
        --rdzv_endpoint=master_worker:29400
        worker.py
    volumes:
      - ./checkpoints:/app/checkpoints
    networks:
      - torch_net

networks:
  torch_net:
    driver: bridge
