apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
  labels:
    app: pytorch-orchestrator
    role: master
spec:
  serviceName: "master-service"
  replicas: 1
  selector:
    matchLabels:
      app: pytorch-orchestrator
      role: master
  template:
    metadata:
      labels:
        app: pytorch-orchestrator
        role: master
    spec:
      containers:
      - name: pytorch
        # For production, you would push this image to a registry (e.g., Docker Hub, GCR, ECR)
        # and change the image name to something like 'your-registry/pytorch-orchestrator:latest'
        image: pytorch-orchestrator
        # For production, change this to 'IfNotPresent' or 'Always' after pushing to a registry.
        # 'Never' is used for local development where the image is built directly into the local cluster's Docker daemon.
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          WORLD_SIZE=$((1 + $WORKER_REPLICAS))
          echo "Master starting..."
          echo "WORLD_SIZE: ${WORLD_SIZE}"
          echo "RANK: 0"
          export WORLD_SIZE=${WORLD_SIZE}
          export RANK=0
          python -u worker.py --is_master=True
        ports:
        - containerPort: 12345
          name: pytorch-tcp
        env:
        - name: MASTER_ADDR
          value: "master-service"
        - name: WORKER_REPLICAS
          valueFrom:
            configMapKeyRef:
              name: pytorch-config
              key: WORKER_REPLICAS
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - pidof
            - python
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pidof
            - python
          initialDelaySeconds: 10
          periodSeconds: 5