apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: pytorch-orchestrator
    role: worker
spec:
  # NOTE: The number of replicas is configured in 'kubernetes/config.yaml'.
  # You must manually keep this value in sync with the WORKER_REPLICAS in the ConfigMap.
  # For a more advanced setup, use a templating tool like Helm or Kustomize.
  replicas: 1
  serviceName: "worker-service"
  selector:
    matchLabels:
      app: pytorch-orchestrator
      role: worker
  template:
    metadata:
      labels:
        app: pytorch-orchestrator
        role: worker
    spec:
      containers:
      - name: pytorch
        image: pytorch-orchestrator
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Extract the pod's index from its hostname (e.g., 'worker-0' -> '0')
          ORDINAL_INDEX=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)

          # Rank is the ordinal index + 1 (since master is rank 0)
          RANK=$((1 + $ORDINAL_INDEX))

          # World size is the number of workers + 1 master
          WORLD_SIZE=$((1 + $WORKER_REPLICAS))

          echo "Worker starting..."
          echo "HOSTNAME: $HOSTNAME"
          echo "ORDINAL_INDEX: ${ORDINAL_INDEX}"
          echo "RANK: ${RANK}"
          echo "WORLD_SIZE: ${WORLD_SIZE}"
          
          export RANK=${RANK}
          export WORLD_SIZE=${WORLD_SIZE}

          python -u worker.py
        env:
        - name: MASTER_ADDR
          value: "master-service"
        - name: WORKER_REPLICAS
          valueFrom:
            configMapKeyRef:
              name: pytorch-config
              key: WORKER_REPLICAS
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - pidof
            - python
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pidof
            - python
          initialDelaySeconds: 10
          periodSeconds: 5
