name: CI

on: 
  push:
    branches:
      - main
      - feature/ci-cd
  pull_request:
    branches:
      - main
      - feature/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t pytorch-orchestrator:latest .
